### ISSUE TITLE
Viewmodel gets messed up when changing from display mode

### ISSUE THREAD

**Issue by thephoenix107** [momentum-mod/game#1686] opened 2022-02-16 11:07 UTC
### Describe the bug

When changing display mode from fullscreen to fullscreen windowed or vice versa, the textures of the viewmodel can get really dark or really bright.

![20220216115533_1](https://user-images.githubusercontent.com/43836455/154251361-f1991595-2ab2-476e-a0e3-50191ffd6d89.jpg)
![20220216115552_1](https://user-images.githubusercontent.com/43836455/154251373-a0a898fe-82ad-490e-8c89-424f71a0fb3e.jpg)

There is no clear pattern as to whether it becomes darker or brighter.

### How To Reproduce

1. Load a map in fullscreen mode (not consistent throughout different maps, worked every time on surf_be_gentle).
2. Go into video settings and change the display mode to fullscreen windowed.
3. The viewmodel should now be completely dark or really bright.

### Expected Behavior

The textures of the viewmodel should not change when changing the display mode.

### Operating System

Windows 10

### Renderer

DX11 (default)

**Comment by hexaflexahexagon** [comment] 2022-02-16 13:05
duplicate of https://github.com/momentum-mod/game/issues/1674

**Closed as completed by hexaflexahexagon** 2022-02-16 13:05 UTC
Labels: Outcome: Invalid
