### ISSUE TITLE
PC Crashes when opening hl2.exe

### ISSUE THREAD

**Issue by JitterDev** [momentum-mod/game#1171] opened 2020-11-26 00:21 UTC
**Describe the bug**
A clear and concise description of what the bug is. If you have a video of it happening, you may post it here.
No video since my PC will restart

**To Reproduce**
Open hl2.exe

If you have a video with the steps to recreate the bug, please post it here.

**Expected behavior**
A clear and concise description of what is expected to happen.
Open hl2.exe
PC will restart

**Screenshots**
None

**Desktop/Branch (please complete the following information):**
 - OS: [Windows / Linux]
 - Branch: [Steam version / Latest develop branch]
Windows 10, MomentumDev from Google Drive

**Additional context**
I haven't taken a video of this yet. I'll attach a video of it soon

EDIT:
The first time I ran it, it crashed, but after trying again later, it creates weird unexplainable side effects. I will attach a video soon.

**Comment by patrickmoc** [comment] 2020-11-26 00:35
You state you're running the game on "MomentumDev from Google Drive", but this is not the full game. If you're trying to build the game you need to follow the [build guide](https://docs.momentum-mod.org/guide/building-the-game/). If you are just trying to do this to play the game I suggest running the 0.6.2 pre-release or waiting for the public beta.

**Comment by JitterDev** [comment] 2020-11-26 00:45
> You state you're running the game on "MomentumDev from Google Drive", but this is not the full game. If you're trying to build the game you need to follow the [build guide](https://docs.momentum-mod.org/guide/building-the-game/). If you are just trying to do this to play the game I suggest running the 0.6.2 pre-release or waiting for the public beta.

The build guide says "Edit the creategameprojects.ps1 file to point the $path variable to the full path of the MomentumDev folder."
I could not find this file in either the google drive or the GitHub.

**Comment by patrickmoc** [comment] 2020-11-26 00:47
it is [here](https://github.com/momentum-mod/game/blob/c08f2a17f7d5f97954b7fae6dd572364d63fa079/mp/src/creategameprojects.ps1#L11)

**Comment by patrickmoc** [comment] 2020-11-26 00:52
It seems that this is not a bug and just confusion about the build process. Questions about this are more fit for the [discord server](https://discord.gg/n4v52uv). With that in mind I am going to close the issue.

**Closed by patrickmoc** 2020-11-26 00:52 UTC
Labels: Blocked: Needs more info, Type: Bug
