### ISSUE TITLE
Map finished panel redesign/refactor

### ISSUE THREAD

**Issue by braem** [momentum-mod/game#1093] opened 2020-10-27 00:53 UTC
**What feature is your improvement idea related to? Please describe.**
Map finished panel needs some love.

**Describe the solution you'd like**
Refactor/redesign the panel altogether based on a design that is tbd. 

- [x] Mockup
- [x] Move run save/uploading into it's own panel so players can close & keep playing.

**Comment by braem** [comment] 2020-10-27 00:54
Should solve https://github.com/momentum-mod/game/issues/1091

**Comment by ijre** [comment] 2020-10-30 03:35
I wrote a fix for #1091 before noticing you had opened this which would solve it; should I still make a PR considering this issue having the blocked label?

**Comment by braem** [comment] 2020-10-30 07:57
> I wrote a fix for #1091 before noticing you had opened this which would solve it; should I still make a PR considering this issue having the blocked label?

Yeah go ahead, this redesign will happen much later. Just be sure the cvar for enabling movement after map finish still works with your fix.

**Comment by Gocnak** [comment] 2022-02-01 09:02
Dupe of #1509 , will be implicitly closed with that issue.

**Closed** 2022-05-13 16:46 UTC
Labels: Type: Enhancement, Size: Large, Outcome: Resolved
