### ISSUE TITLE
In hammer, PBR does not render correctly on displacements

### ISSUE THREAD

**Issue by Ninja-Cookie** [momentum-mod/game#2027] opened 2023-03-13 03:53 UTC
### Describe the bug

PBR on displacements renders totally black within hammer, unless selected
![image](https://user-images.githubusercontent.com/62808028/224604290-3c9151e7-deee-411b-b929-b5aa2571f167.png)
![image](https://user-images.githubusercontent.com/62808028/224604372-a6647a70-e05d-4d1f-8aca-7e5a27b0b257.png)

### How To Reproduce

Download this test VMF with a PBR materiel:
[test_pbr_disp.zip](https://github.com/momentum-mod/game/files/10953366/test_pbr_disp.zip)

### Issue Map

N/A

### Expected Behavior

Render as normal.

### Operating System

Windows

**Comment by tmob03** [comment] 2023-03-13 04:23
Duplicate of https://github.com/StrataSource/Chaos-Source/issues/660

**Comment by Gocnak** [comment] 2024-03-09 06:21
Should be fixed in latest release

**Closed as completed by Gocnak** 2024-03-09 06:21 UTC
