### ISSUE TITLE
Letters used for localization can't be typed but do showup in names.

### ISSUE THREAD

**Issue by tricksurf** [momentum-mod/game#859] opened 2020-07-25 20:31 UTC
**Describe the bug**
Letters such as "ç è é ô î û â à ë œ" (to name a few), can't be typed in game, they don't show up after attempting the keystroke.  

**To Reproduce**
In my case:
1. Get another language on keyboard, that uses symbols.
2. Alt + Shift
3. Try typing any of them
 - For me, French Canadian and ' = è / = é, blah blah blah

**Expected behavior**
Should be able to type the symbols, especially useful for people who don't speak English as their first language.

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by Gocnak** [comment] 2020-07-25 20:33
Duplicate of https://github.com/momentum-mod/game/issues/851 ? Or is this something else

**Comment by tricksurf** [comment] 2020-07-25 22:20
> Duplicate of #851 ? Or is this something else

Oh I didnt see that since it was closed, my bad

**Comment by Gocnak** [comment] 2020-07-25 22:23
No problem!

**Closed by Gocnak** 2020-07-25 22:23 UTC
Labels: Type: Bug
