### ISSUE TITLE
Can't edit key to change console bind in settings

### ISSUE THREAD

**Issue by itVictor** [momentum-mod/game#884] opened 2020-08-06 19:31 UTC
**Describe the bug**
Attempting to change the key used to open the console from settings (under input > keybinds) will not work. You can change the key in the field but trying out the change will not work, the key you inputted will not be binded and ` will still open it.

**To Reproduce**
Open settings, go to input > keyboard and change the bind to open the console. Close the settings page and observe that \` is still binded to open the console and your new key does nothing. Reopening the settings page shows that \` is still binded to open the console.

**Expected behavior**
Should be able to change the bind with no issues.

**Desktop (please complete the following information):**
 - OS: Windows

**Comment by Lightningblade** [comment] 2020-08-15 01:28
I've just tried changing the key and it works fine, so I can't reproduce it.

A temporary fix would be  ```bind f11 "toggleconsole"```.

**Comment by braem** [comment] 2020-09-02 19:19
A LOT of stuff relating to this is in the engine. I pushed a wip commit if anyone wants to try to tackle further: `bug/console-toggle-keybind`.

**Comment by lvaness** [comment] 2021-08-06 15:23
Is this still an issue on Panorama? I can't reproduce it there.

**Comment by hexaflexahexagon** [comment] 2021-08-06 15:29
Rebinding the console key seems to work OK but you have to use ` to close the console still it seems and your new bind won't work? but that'd be unrelated to this issue so I'll close it for now

**Closed by hexaflexahexagon** 2021-08-06 15:29 UTC
Labels: Type: Bug, Blocked: Needs testing & verification, Priority: Low
