### ISSUE TITLE
Skyname is kept between maps

### ISSUE THREAD

**Issue by VortexParadox** [momentum-mod/game#1823] opened 2022-06-05 18:34 UTC
### Describe the bug

If a map has a custom skybox it will still be referenced after changing a map. This wouldn't be a problem for other maps that do set their skybox name, but for maps that leave the propery blank, expecting to just use the default skybox, it will try to load the custom skybox from the previous map. Which will fail and make the skybox a hall of mirrors mess, with pretty bad performance when looking at an area with `toolsskybox`
<br>
![image](https://user-images.githubusercontent.com/35622748/172065073-439d94ae-2013-4d69-a623-0d7adbc325b9.png)

### How To Reproduce

1.  Load any map that is known to use a custom skybox. (`bhop_furret` was used in my testing)
2.  Afterwards, load a map that does not set the skyname

### Issue Map

| **Test Map:  `dev_SPLCompiles.bsp`** |
| :---: |
| <img src="https://user-images.githubusercontent.com/35622748/172064830-b00c9ad6-94ee-4443-bbf9-26e226f4a6b2.png" width=450> |
| [Download](https://github.com/momentum-mod/game/files/8840503/dev_splcompiles.zip)|

### Expected Behavior

Skyname could be cleared after leaving a map, or have the skyname use the default when a map doesn't specify one

### Operating System

Windows 10

### Renderer

DX11 (default)

**Comment by SlidyBat** [comment] 2022-06-06 12:20
Duplicate of #1677, closing in favour of that. Thanks for the clear repro steps & linking map though, helped to quickly figure out problem.

**Closed as completed by SlidyBat** 2022-06-06 12:20 UTC
