### ISSUE TITLE
Rocket Jumping: The Original doesn't fire from the center actually

### ISSUE THREAD

**Issue by Shirge** [momentum-mod/game#1941] opened 2022-11-28 16:06 UTC
### What feature is your improvement idea related to?

So basically the the center rocket launcher in Momentum Mod seems to fire from the center, but actually the Original doesn't fire from the center.
TF2 only gets rid the 12 units of y offset (y offset is responsible for making the rocket come from the right) it doesn't change the -3 units of z offset (z offset is the vertical offset).
This means that when you fire down at the ground you should be pushed forwards not backwards like in Momentum Mod.
Oh yeah the normal rocket launcher and the Cowmangler also has the -3 z offset so the side and the hybrid rocket launcher are both also wrong probably.

Source:
https://www.youtube.com/watch?v=DXNM-EPPVcQ

### Describe the solution you'd like

Add the offset to the rocket launcher.

### Additional context

Oh also there's a chance that you might have missed the 23.5 x offset (x offset is the one that makes the rocket come from behind).
So you might have to add that.

**Comment by chovelyoukai** [comment] 2022-11-28 23:01
We already account for the offset on all rocket launchers. Did you notice something in the game to report this?

**Comment by hexaflexahexagon** [comment] 2022-11-29 00:19
> ... you should be pushed forwards not **backwards like in Momentum Mod**

when shooting straight down in momentum I do go forwards as well so I can't replicate this

**Comment by Ninja-Cookie** [comment] 2022-11-29 02:37
This is an overlay of Momentum Mod and Team Fortress 2 using all 3 weapons in both Standing and Crouched. You can barely even tell it has an overlay of Momentum Mod because it syncs up perfectly other than damage view knock and some smoother frames in Momentum Mod while falling. You land in the exact same places from shooting directly down.
https://user-images.githubusercontent.com/62808028/204424628-dd226675-e5d6-4b3a-ac2a-5da2f25fa64d.mp4

**Comment by Shirge** [comment] 2022-12-01 16:29
> This is an overlay of Momentum Mod and Team Fortress 2 using all 3 weapons in both Standing and Crouched. You can barely even tell it has an overlay of Momentum Mod because it syncs up perfectly other than damage view knock and some smoother frames in Momentum Mod while falling. You land in the exact same places from shooting directly down. https://user-images.githubusercontent.com/62808028/204424628-dd226675-e5d6-4b3a-ac2a-5da2f25fa64d.mp4

ok

**Comment by VortexParadox** [comment] 2022-12-01 17:41
Closing since we cannot reproduce/is not an issue

**Closed as not planned** 2022-12-01 17:42 UTC

**Comment by Shirge** [comment] 2022-12-02 14:51
> Closing since we cannot reproduce/is not an issue

ok
