### ISSUE TITLE
Pain markers are rotated when going through a portal that rotates

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1797] opened 2022-05-05 03:05 UTC
### Describe the bug

Jumping through a portal that rotates the player (changes their view as if they moved the mouse) will consequently re-orient their painmarkers. E.g. if portal 1 is facing north, portal 2 is facing south, doing a stickyjump through portal 1 will result in your pain markers snapping 180 degrees upon exiting portal 2.

### How To Reproduce

1. Load `bhop_tripportals`
2. Step onto any of the blocks
3. Turn around and do a stickyjump through the portal infront of you
4. Notice the painmarkers

### Issue Map

Any with portals oriented this way, but `bhop_tripportals` is an official map that the issue can be replicated on

### Expected Behavior

painmarkers move as expected

### Operating System

windows 10

### Renderer

DX11 (default)

**Comment by Gocnak** [comment] 2022-05-11 15:01
Pain markers are drawn from the origin of the damage. I'm not really sure what this issue is, you being teleported through a portal would absolutely affect it as if you rotated your view manually with your mouse.

There's no real way to make damage indicators relative in this case. I'm feeling like this is a won't fix/working as intended.

**Comment by hexaflexahexagon** [comment] 2022-05-11 15:39
the issue is just that it "looks weird," nothing actually wrong since it does make sense currently if you sit back and actually think it through. i figured it wouldn't be too difficult to add 180 degrees of offset when going through a portal to all active markers or something along those lines, but if that's not feasible maybe we should not bother with this. I'd rather keep it open and add the blocked tag than a "wontfix" though, it does look incredibly strange when you first notice it on a seamless portal. (on the off chance someone has a good idea on mitigating this in 2 years from now)

**Comment by lvaness** [comment] 2022-05-11 19:30
If we had any kind of event firing on portal traversal that specified the portal's plane, the exit point and the angle of rotation it should be possible to come up with the dummy point that represents the expected angle

**Comment by Gocnak** [comment] 2024-09-20 21:30
Closing, I think the only time this is going to be an actual issue will be if you're standing right at the edge of a portal and blasting through it. Damage HUD is for when you're detonating / getting hit, and its data loses its value quickly after that happens, so rotating is fine.

**Closed as not planned by Gocnak** 2024-09-20 21:30 UTC
