### ISSUE TITLE
"View on docs" button doesn't use new docs URLs

### ISSUE THREAD

**Issue by tsa96** [momentum-mod/game#2086] opened 2023-07-29 23:10 UTC
When migrating the docs to Hugo we changed various URLs, breaking the "View on docs" button.

This should be an easy fix - figure out what pattern the new URLs are using (I can't remember - sorry!) and change the JS for it. Should be a 1-2 line fix.

**Comment by Mac-tf2** [comment] 2024-04-09 18:55
can't find any broken urls caused by the JS, closing

**Closed as not planned by Mac-tf2** 2024-04-09 18:55 UTC
Labels: Priority: High, Size: Trivial, Where: UI
