### ISSUE TITLE
Paint gun preview panel renders weirdly in cl_righthand 0

### ISSUE THREAD

**Issue by Gocnak** [momentum-mod/game#257] opened 2019-05-22 02:59 UTC
It's like flipped or something, the panel should correct itself to display properly for right or lefthanded.

**Comment by braem** [comment] 2020-05-10 02:27
In the .qc file for the paintgun, the two attachment points are the same: 
`$attachment "controlpanel0_ur" "Screen_UpperRight" 0.0 0.0 0.0 rotate 0 0 -20`
`$attachment "controlpanel0_ll" "Screen_LowerLeft" 0.0 0.0 0.00 rotate 0 0 -20`

Might be the cause? I feel the VGUI screen should stay properly attached with the current code as it does follow the viewmodel when it's flipped.

**Comment by tsa96** [comment] 2020-05-19 20:47
PaintGunScreenPanel::Paint() doesn't actually seem to be being called with cl_righthand 0

**Comment by braem** [comment] 2020-08-08 17:55
Closing as will be resolved by implementing https://github.com/momentum-mod/game/issues/886

**Closed by braem** 2020-08-08 17:55 UTC
Labels: Priority: Low, Size: Medium, Type: Bug
