### ISSUE TITLE
PB and WR notifications in lobby chat

### ISSUE THREAD

**Issue by yasiralamriki** [momentum-mod/game#1694] opened 2022-02-22 02:16 UTC
### What feature is your improvement idea related to?

It would be nice to see your personal best and world records in chat 

### Describe the solution you'd like

![image](https://user-images.githubusercontent.com/70416702/155050549-3b480fd4-0539-4987-b90f-defed559d1af.png)
this is an image of a plugin in a surf server on CSGO of what it would look like, I am not a pro designer so I can't give an idea of what this would look like but this is a mockup
[WR] {name} achieved a world record of {time} on {map}. {place}
[PB] {name} achieved {new time} beat their personal best {past time} by {new time - past time} 

### Describe alternatives you've considered, if any.

One alternative is having a seperate channel in chat that goes across all lobbies and would only show world records, and then lobby chat would show personal bests

**Comment by Gocnak** [comment] 2022-03-08 09:52
Duplicate of #1543

**Closed as completed by Gocnak** 2022-03-08 09:52 UTC
