### ISSUE TITLE
resolution bugs

### ISSUE THREAD

**Issue by noooaaahhhh** [momentum-mod/game#1882] opened 2022-09-17 11:31 UTC
### Describe the bug

https://streamable.com/hz02k6

any res other than 1920x1080 doesn't rly work when you go ingame it just doens't go fullscreen. You can put the launch options as the res you want it will actually work but makes your game extremely laggy and as soon as you tab out it will just go to a windowed thing again.

### How To Reproduce

If you put the launch options as a random res it will be rly laggy and if you try to change the res to anything other than 1920x1080 it won't actually go fullscreen.

### Issue Map

-

### Expected Behavior

Just want other resolutions to work, 4:3 1280x960 

### Operating System

windows

### Renderer

DX11 (default)

**Comment by Shegetz** [comment] 2022-09-17 11:57
duplicate of https://github.com/momentum-mod/game/issues/1761

**Comment by chovelyoukai** [comment] 2022-09-17 11:59
I don't think this is a duplicate of that issue. That issue addresses UI problems, this one is about performance and fullscreen.

**Comment by chovelyoukai** [comment] 2022-09-17 12:00
Could probably be made into two issues, one addressing the lag, one addressing the fullscreen<->windowed issue.

**Comment by Shegetz** [comment] 2022-09-17 12:01
fair enough I just understood the other issue to be generalized support for other aspect ratios and felt like this one fell under that

**Comment by chovelyoukai** [comment] 2022-09-17 12:03
I think if we have any more aspect ratio problems, we could maybe make a project to track them. This looks to me like a renderer/DX11 problem and not related to Pano, at least not obviously, so imo it should be tracked separately.

**Comment by SlidyBat** [comment] 2022-10-12 13:06
I suspect this is the same issue as https://github.com/momentum-mod/game/issues/1915.
When alt-tabbing, the game switches to windowed, then goes back to fullscreen when focus is regained.
Since game wasn't correctly detecting when focus is regained, it didn't do the switch back to fullscreen.

As for the lag, that is probably also caused by window not having focus; with `engine_no_focus_sleep` the game tries to decrease CPU utilization when it doesn't have focus.

Please retest next update and let us know if this is still an issue for you.

**Comment by SlidyBat** [comment] 2022-10-16 16:27
~~Haven't heard back from any playtesters about this.
Going to tentatively close this, and we can reopen if we find out there are any more issues.~~

(Wrong issue 🤦)

**Comment by Gocnak** [comment] 2023-05-11 05:18
Hi, is this still an issue?

**Comment by Gocnak** [comment] 2023-09-16 20:04
Hi, I will be closing this issue unless this persists on the latest version of Momentum, in which case we can reopen and continue investigating the cause.

**Closed as completed by Gocnak** 2023-09-16 20:04 UTC
Labels: Blocked: Needs testing & verification
