### ISSUE TITLE
clicking anywhere in settings scrolls to top

### ISSUE THREAD

**Issue by rdg11** [momentum-mod/game#1951] opened 2022-12-07 04:23 UTC
### Describe the bug

whenever you click a subcategory in the settings e.g. "Rocket Jump" in the "Gameplay" tab, then click anywhere within the middle column of the settings page (besides the buttons/toggles) it auto scrolls back up to the top of the main category e.g. "Gameplay".

### How To Reproduce

Open Settings
Click on a category e.g. "GAMEPLAY"
Click on a subcategory e.g. "ROCKET JUMP"
Click anywhere within the middle column, which is not a button or slider.
It should automatically scroll you back to the top (not intended)

### Issue Map

- not a map bug -

### Expected Behavior

when you click anywhere, nothing should happen.

### Operating System

Windows 10

### Renderer

DX11 (default)

**Comment by tsa96** [comment] 2023-06-06 20:16
Duplicate of https://github.com/momentum-mod/game/issues/1863

**Closed as not planned by tsa96** 2023-06-06 20:16 UTC
Labels: Where: UI
