### ISSUE TITLE
Split data rarely does not update correctly

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1113] opened 2020-10-30 11:49 UTC
**Describe the bug**
Checkpoint data can carry over from one map to another if 1. the next map has no pr's saved and 2. the HUD timer is disabled with `mom_hud_timer 0`.

**To Reproduce**
The steps to reproduce appear to be:
1. run a map until at least checkpoint, which shows a split comparison on the timer HUD element
2. disable the timer with `mom_hud_timer 0`
3. load a new map with no pr (that has zones)
4. play the second map until checkpoint 2 or further
5. re-enable the timer with `mom_hud_timer 1`

**Expected behavior**
There should be no split data on a map with no previous completion (when comparing against pr)

**Desktop/Branch (please complete the following information):**
 - OS: Windows
 - Branch: Steam version

**Comment by Gocnak** [comment] 2020-10-31 09:20
I think this bug comes from the fact that you hide your timer only sometimes. Something to try for me: hide your timer, finish a run on a zoned map with comparisons, load a map without PB, then start a run and get to past zone 1 (checkpoint 2 or Stage 2).

Toggle your timer HUD on. It should cause this bug now.

Something to verify: entering practice mode during this run OR canceling your time (mom_timer_stop) should clear it and it should be good.

Then something else to verify: do the exact same steps, but before turning the HUD timer back on, enter practice mode and exit it, and see if it doesn't compare.

I know what the problem is if what I asked to verify turns out true. It's because the labels aren't being cleared because the method for updating them (`OnThink()`) isn't being run when the timer is hidden. So the fix for this would be trivial and just a matter of overriding `LevelInit()` and calling `SetToNoTimer()` in there.

**Comment by hexaflexahexagon** [comment] 2020-10-31 10:17
> I think this bug comes from the fact that you hide your timer only sometimes. Something to try for me: hide your timer, finish a run on a zoned map with comparisons, load a map without PB, then start a run and get to past zone 1 (checkpoint 2 or Stage 2).
> 
> Toggle your timer HUD on. It should cause this bug now.

Tested, this is exactly what happens


> Something to verify: entering practice mode during this run OR canceling your time (mom_timer_stop) should clear it and it should be good.

Also tested, this is correct as well.


> Then something else to verify: do the exact same steps, but before turning the HUD timer back on, enter practice mode and exit it, and see if it doesn't compare.

The bug was still there when I exit'd practice mode and then enabled the hud timer.


Also as your theory would imply, finishing the map seems to be unnecessary. Just having any split data on the hud timer and then disabling it before loading a new map recreates as well.

**Closed** 2020-11-02 04:01 UTC
Labels: Priority: High, Size: Trivial, Type: Bug
