### ISSUE TITLE
Console New Line Sometimes Displays Incorrectly

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1054] opened 2020-10-21 07:29 UTC
**Describe the bug**
sometimes console commands fail to correctly return to a new line. this can happen with multiple commands but anecdotally it is the most common with `getpos`. I believe could be due to the timing of when certain text is output to console

**To Reproduce**
1. Type `getpos` multiple times until it happens

**Expected behavior**
The lines should display in the correct order

**Screenshots**
![image](https://user-images.githubusercontent.com/62961532/96686867-1b845900-134d-11eb-8c45-e613fbd41986.png)

**Desktop/Branch (please complete the following information):**
 - OS: Windows
 - Branch: Develop

**Additional context**
`echo hello` and `r_dynamic` have also triggered this bug

**Comment by McGravel** [comment] 2020-10-21 07:32
Is this a duplicate of #949 ?

**Comment by braem** [comment] 2020-10-21 07:32
Looks like a duplicate of https://github.com/momentum-mod/game/issues/949

**Closed** 2020-10-21 07:34 UTC
Labels: Type: Bug
