### ISSUE TITLE
Modernized weapon-switch hud menu

### ISSUE THREAD

**Issue by braem** [momentum-mod/game#1306] opened 2021-04-17 01:12 UTC
**What feature is your improvement idea related to? Please describe.**
The HL2 weapon switch menu is quite dated; it shows only when `hud_fastswitch 0`, and requires an additional action (`+attack`) to actually switch weapons. To switch weapons quickly, you will need `hud_fastswitch 1`, but then you don't get a good idea of what weapons you have equipped and the keybinds for them.

With panorama, we can make a much better looking one with a more modern workflow.

**Describe the solution you'd like**
Newer games have a better system of always showing your weapons in a succinct manner with the current one highlighted, or having the menu pop up and fade when switching. Also properly show the keybind for the specific slot instead of just 1, 2, 3, etc.

Will require UI/UX design.

**Additional Context*
Maybe something to include in the base engine?? Might be nice to have the same weapon HUD menu system for all chaos games. Though this would require significant refactoring and centralizing of weapon systems I imagine.

**Comment by braem** [comment] 2021-04-17 07:59
Actually im dumb and we have a mockup for this already.
![image](https://user-images.githubusercontent.com/9014762/115106180-23960d80-9f18-11eb-83f5-fecbf3787ab9.png)

**Comment by Gocnak** [comment] 2021-04-20 02:32
Yep the idea is that fastswitch is always on but pressing the keys just cycles through and this small and compact UI shows it. Gonna be a fun one to implement! :)

**Comment by Gocnak** [comment] 2022-02-01 08:55
Sorta dupe of #1512 , implicitly closed with that issue.

**Closed as completed** 2022-02-21 07:15 UTC
Labels: Size: Large, Outcome: Resolved, Where: Game
