### ISSUE TITLE
Lobby Host closing game with X button will crash all players in the Lobby

### ISSUE THREAD

**Issue by McGravel** [momentum-mod/game#412] opened 2019-10-10 02:15 UTC
> "There's a crash for lobbies where the host? clicks "X" on the game window, it crashes for everyone in the lobby apparently"

**Comment by McGravel** [comment] 2019-11-16 17:26
Potentially related to #462 ?

**Comment by Gocnak** [comment] 2019-11-20 20:21
Closing due to not being able to reproduce it easily. Can re-open if steps are described in the future.

**Closed by Gocnak** 2019-11-20 20:21 UTC
Labels: Blocked: Needs more info, Priority: Medium, Type: Bug
