### ISSUE TITLE
Filename independent cubemaps

### ISSUE THREAD

**Issue by lvaness** [momentum-mod/game#1202] opened 2020-12-19 17:16 UTC
**Is your feature request related to a problem? Please describe.**
When renaming a map's bsp, cubemaps will not be loaded correctly anymore since their paths inside the pakfile are dependent on the map's name. This is especially annoying since rebuilding cubemaps is rather involved and may require changing settings in-game to get the best results while name-changes can occur often for testing/mapping purposes. Many maps from the ingame map selector even have broken cubemaps for this reason.

This is a really unintuitive trap for inexperienced mappers and unsuspecting players alike.

**Describe the solution you'd like**
When building cubemaps, add a [game lump](https://developer.valvesoftware.com/wiki/Source_BSP_File_Format#Game_lump) inside the bsp containing the path where the cubemaps are. Then, when loading the map and its cubemaps, first try the standard path, then - if it exists - look inside the game lump for the path, then if all fails, fallback to default.

**Describe alternatives you've considered**
Cubemap folders could just have map-independent names. This would break bsp compatibility to other source games, though.

Edit: Now that I think about it, just adding a text file containing the paths to the pak in some format might be much easier and more portable.

**Comment by Gocnak** [comment] 2021-03-18 17:08
Potential solution is to use the MD5/SHA1 hash of the map? Map header may already even have the hash, the problem is inserting a texture into the map changes the hash...

Maybe making the hash only on a specific lump? Only for cubemaps?

**Comment by lvaness** [comment] 2021-03-19 23:32
Yeah I could see something with a hash working, but I don't know based on what either. Ideally if you change any packed textures it should "invalidate" the cubemaps by changing the hash, which of course is a bad idea since you also need to pack the cubemap. On the other hand, if you changed the packed files of a map you should already know what you're doing, so just skipping it might be OK.

**Comment by Gocnak** [comment] 2021-07-16 00:38
What about the texture data lump? Something that changes when you change the texture data in the BSP.

**Comment by Gocnak** [comment] 2024-08-10 00:02
Closing in favor of https://github.com/StrataSource/Engine/issues/1202

**Closed as not planned by Gocnak** 2024-08-10 00:02 UTC
Labels: Where: Engine
