### ISSUE TITLE
While crouched on ramp, indicate to the player that you are still ducked

### ISSUE THREAD

**Issue by Beetle179** [momentum-mod/game#269] opened 2019-06-15 18:08 UTC
If you uncrouch while on a ramp, your player will actually remain crouched (including the negative airaccel effects + hitbox size). You will immediately uncrouch as soon as you are able to (normally, when you leave the ramp). (Think of it like uncrouching while under a very low ceiling -- your character won't stand up because they can't. Behaves the same way)

The suggestion is that, in these cases where you're not holding the crouch button but the game is keeping you crouched anyway, keep the "Duck" icon in the bottom-right lit up (or perhaps in a different color; red?)

(I love this suggestion)

Suggested by Sneakyy

**Comment by SlidyBat** [comment] 2019-06-19 04:26
Duplicate of #259

**Closed by SlidyBat** 2019-06-19 04:26 UTC
Labels: Size: Medium, Type: Enhancement
