### ISSUE TITLE
Improve console autocompletion

### ISSUE THREAD

**Issue by zachconnor** [momentum-mod/game#1684] opened 2022-02-16 08:26 UTC
### What feature is your improvement idea related to?

Using the Momentum console has some differences from other Source game consoles that breaks muscle memory despite other improvements. The main difference is that pressing down no longer auto-fills the textbox.

### Describe the solution you'd like

When pressing down in the console while autocompletion suggestions are shown, it should autofill in the textbox as you press down.

### Additional context

I compared the experience in Momentum to the consoles in both CSS and CSGO, but didn't check any other source games. I think this should be a reasonable addition that complements the scrollable autocompletion box.

**Comment by hexaflexahexagon** [comment] 2022-02-16 12:59
Duplicate of #1527 / #1540

**Closed as completed** 2022-02-16 13:00 UTC
Labels: Outcome: Invalid
