### ISSUE TITLE
Stickybombs shot in the middle of two portals stick in mid-air

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1460] opened 2021-07-19 17:14 UTC
**Describe the bug**
Like the title says, standing directly inbetween two portals (when you see the white line like https://github.com/momentum-mod/game/issues/1404) and shooting a stickybomb will result in the image below. Works on any portal as far as I can tell.

![image](https://user-images.githubusercontent.com/62961532/126199751-ac23c393-69af-4910-a909-c0f4161db457.png)

I'm unsure if this is the same as https://github.com/momentum-mod/game/issues/1456. Also this may have been caused by the solution to https://github.com/momentum-mod/game/issues/1402? I don't remember how exactly that was fixed but I know stickies can stick on the edges of freestanding portals now because of it, which could be related.

**Comment by braem** [comment] 2022-03-09 06:03
Duplicate of https://github.com/momentum-mod/game/issues/1456

**Closed as completed by braem** 2022-03-09 06:03 UTC
Labels: Priority: Medium
