### ISSUE TITLE
Entering end zone with hud disabled softlocks the game

### ISSUE THREAD

**Issue by JosSamLoh** [momentum-mod/game#1342] opened 2021-05-23 16:09 UTC
**Describe the bug**
While disabling the hud via the command `cl_drawhud 0` and then entering the end zone, you are practically softlocked, I've attempted using a bind to toggle the hud but I cannot seem to use it once in the end zone.

**To Reproduce**

1. Disable the hud via `cl_drawhud 0`
2. Enter an end zone after starting a run

**Expected behavior**
Being able to toggle the hud via a bind, or being able to enter into the console from the end zone menu while hud is disabled.

**Desktop/Branch (please complete the following information):**
 - OS: **Linux**
 - Branch: **Steam version**

**Comment by braem** [comment] 2021-05-23 17:29
Happens on Windows as well. This is because of the end stats popup requiring a click to exit.

Will be addressed once we switch that over to panorama.

**Comment by hexaflexahexagon** [comment] 2022-04-26 02:16
i can't replicate this anymore with the pano hud element, though not sure if we should close it because there are still some strange interactions between end of run and drawhud 0. namely, if you finish a run with `drawhud 0` then at any point enable it again the end of run will always be present, even if you're halfway through your next run. the only thing that reliably updates it is if you _finish_ another run then enable your hud again, at which point you'll see your new data. maybe if the hud is disabled the panel should just refuse to draw in the first place?

**Comment by Gocnak** [comment] 2022-04-28 07:14
> then at any point enable it again the end of run will always be present  

This is by design, we want the end of run panel to go away when the user manually tells it to go away. This should happen even when visible (try opening/closing leaderboards again and then reset), and is by design.

**Comment by hexaflexahexagon** [comment] 2022-05-13 16:07
it still feels like a bug UX-wise when you're halfway through your 3rd incomplete run and enable your hud, just to see an end of run from 10 minutes ago. the original card is definitely resolved though so if we decide to address this it can happen later and in a new card

**Closed as completed by hexaflexahexagon** 2022-05-13 16:07 UTC
Labels: Priority: High, Size: Small, Outcome: Resolved, Where: Game
