### ISSUE TITLE
Panorama: Warn on loading map without required textures mounted

### ISSUE THREAD

**Issue by Arkanoid0** [momentum-mod/game#1742] opened 2022-03-27 23:51 UTC
### Is your feature request related to a problem?

Currently there is no popup warning when trying to play a map that requires textures mounted that the player doesn't have

### Describe the solution you'd like

Warn when trying to load a map that requires textures mounted, EG surf_utopia.
Integration with future mounted content manager.

**Comment by Mac-tf2** [comment] 2022-03-27 23:55
duplicate of #682

**Closed as completed by Mac-tf2** 2022-03-27 23:55 UTC
